language: node_js
node_js:
  - node
before_install:
  - export CYPRESS_CACHE_FOLDER=.cypress_cache
cache:
  directories:
    - node_modules
    - .cypress_cache
jobs:
  include:
    - stage: lint
      name: "Lint library"
      script: yarn lint:lib
    - script: yarn lint:site
      name: "Lint site"
    - stage: test
      name: "Test library"
      script: yarn test
stages:
  - lint
  - test
